/**
 * API Response Codes — standardized across all endpoints.
 * Naming: {HTTP_STATUS}{SEQUENCE}  2xxx=Success 4xxx=ClientError 5xxx=ServerError
 */
export enum ResponseCode {
  OK = 2000,
  CREATED = 2001,
  ACCEPTED = 2002,
  NO_CONTENT = 2004,
  PARTIAL_SUCCESS = 2006,
  BAD_REQUEST = 4000,
  VALIDATION_ERROR = 4001,
  NOT_FOUND = 4002,
  ALREADY_EXISTS = 4003,
  CONFLICT = 4009,
  UNAUTHORIZED = 4010,
  INVALID_TOKEN = 4011,
  TOKEN_EXPIRED = 4012,
  FORBIDDEN = 4030,
  RATE_LIMITED = 4029,
  REQUEST_TIMEOUT = 4008,
  PAYLOAD_TOO_LARGE = 4013,
  UNSUPPORTED_MEDIA_TYPE = 4015,
  INTERNAL_ERROR = 5000,
  SERVICE_UNAVAILABLE = 5003,
  DB_ERROR = 5002,
  GATEWAY_TIMEOUT = 5004,
  EXECUTION_FAILED = 5005,
  NOT_IMPLEMENTED = 5001,
}

export const RESPONSE_MESSAGES: Record<ResponseCode, string> = {
  [ResponseCode.OK]: 'Success',
  [ResponseCode.CREATED]: 'Resource created successfully',
  [ResponseCode.ACCEPTED]: 'Request accepted for processing',
  [ResponseCode.NO_CONTENT]: 'No content',
  [ResponseCode.PARTIAL_SUCCESS]: 'Partial success — some items may have failed',
  [ResponseCode.BAD_REQUEST]: 'Invalid request — check parameters',
  [ResponseCode.VALIDATION_ERROR]: 'Validation failed',
  [ResponseCode.NOT_FOUND]: 'Resource not found',
  [ResponseCode.ALREADY_EXISTS]: 'Resource already exists',
  [ResponseCode.CONFLICT]: 'Request conflicts with current state',
  [ResponseCode.UNAUTHORIZED]: 'Authentication required',
  [ResponseCode.INVALID_TOKEN]: 'Invalid or malformed token',
  [ResponseCode.TOKEN_EXPIRED]: 'Authentication token has expired',
  [ResponseCode.FORBIDDEN]: 'Access denied — insufficient permissions',
  [ResponseCode.RATE_LIMITED]: 'Too many requests — slow down',
  [ResponseCode.REQUEST_TIMEOUT]: 'Request timed out',
  [ResponseCode.PAYLOAD_TOO_LARGE]: 'Request payload exceeds size limit',
  [ResponseCode.UNSUPPORTED_MEDIA_TYPE]: 'Unsupported content type',
  [ResponseCode.INTERNAL_ERROR]: 'Internal server error',
  [ResponseCode.SERVICE_UNAVAILABLE]: 'Service temporarily unavailable',
  [ResponseCode.DB_ERROR]: 'Database operation failed',
  [ResponseCode.GATEWAY_TIMEOUT]: 'Upstream service timeout',
  [ResponseCode.EXECUTION_FAILED]: 'Workflow execution failed',
  [ResponseCode.NOT_IMPLEMENTED]: 'Feature not implemented',
};
